name: Run tests on pull requests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true

      - name: Build with Maven
        run: mvn clean test