name: Build latest master and deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, self-hosted ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 22
          java-distribution: liberica
          checkout-persist-credentials: true
          cache-enabled: false
          settings-servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package

      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/valorant-premier-bot
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create-manifest
        run: |
          docker manifest create bjoggis/valorant-premier-bot:${{ github.ref_name }} --amend bjoggis/valorant-premier-bot:${{ github.ref_name }}-x86_64 --amend bjoggis/valorant-premier-bot:${{ github.ref_name }}-aarch_64
          docker manifest push bjoggis/valorant-premier-bot:${{ github.ref_name }}
          docker manifest create bjoggis/valorant-premier-bot:latest --amend bjoggis/valorant-premier-bot:${{ github.ref_name }}-x86_64 --amend bjoggis/valorant-premier-bot:${{ github.ref_name }}-aarch_64
          docker manifest push bjoggis/valorant-premier-bot:latest
